sudo: false
language: ruby
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile
script:
  - "bundle exec rspec"
matrix:
  exclude:
  - rvm: 2.3.8
    gemfile: gemfiles/6.0.gemfile
  - rvm: 2.4.9
    gemfile: gemfiles/6.0.gemfile